- addons/sourcemod/scripting/eq_finale_tanks.sp
- addons/sourcemod/scripting/l4d2_fireworks_noise_block.sp
This version of eq_finale_tanks replace bridge_escape_fix.sp, also this with more accurate method blocks escape tanks,
also this version do not make tank counting if map not in tank_map_flow_and_second_event or tank_map_only_first_event (status of spawnScheme  is Skip  in this case but original plugin was do counting that absolutly not need)
> This version of eq_finale_tanks replace bridge_escape_fix.sp

- addons/sourcemod/scripting/include/confogl.inc
LGO_OnMatchModeLoaded is repeated instead of LGO_OnMatchModeUnloaded
> fix LGO_OnMatchModeUnloaded forward prototype

- addons/sourcemod/scripting/caster_assister.sp
This feature existed in [caster_assister v1.0.1](https://github.com/SirPlease/ZoneMod/blob/e44044669636af8cc7797f4897d0184a0b021f27/addons/sourcemod/plugins/optional/zonemod/caster_assister.smx) before the recent crash exploit fix in v2.1. I think this was removed unintentionally so this PR adds it back.
Also, [Server4Dead-Project](https://github.com/SirPlease/Server4Dead-Project/blob/master/Competitive%20Configs/addons/sourcemod/plugins/optional/zonemod/caster_assister.smx) never got updated with the crash exploit fix like the ZoneMod repo did, so it's still using version 1.0.1.
> execute sm_spechud for casters joining the server

- addons/sourcemod/scripting/confoglcompmod.sp
- addons/sourcemod/scripting/include/l4d2_direct.inc
- addons/sourcemod/scripting/l4d2_godframes_control_merge.sp
- addons/sourcemod/scripting/l4d2_uniform_spit.sp
- addons/sourcemod/scripting/modules/EntityRemover.sp
- addons/sourcemod/scripting/modules/GhostWarp.sp
- addons/sourcemod/scripting/modules/ItemTracking.sp
- addons/sourcemod/scripting/modules/MapInfo.sp
- addons/sourcemod/scripting/modules/PasswordSystem.sp
- addons/sourcemod/scripting/modules/SI_Targeting.sp
These are all cases where MAXPLAYERS and MaxClients are used to create client arrays or they're used in a loop involving a client index or being compared to a client index.
For the one change in `addons/sourcemod/scripting/modules/EntityRemover.sp`, I referred to this [alliedmodders post](https://forums.alliedmods.net/showpost.php?p=1710686&postcount=11) to determine that the loop in is starting off with the wrong index.
> fix MaxClients and MAXPLAYERS off by one errors

- addons/sourcemod/gamedata/left4dhooks.l4d2.txt
This seems to work fine as is, but according to asherkin it could cause bugs crashes. This adds support for the new `bool& allow_boss_mix` parameter on `CDirector::GetMissionVersusBossSpawning`.
SilverS was reporting this change as well. I'm sure we'll eventually pull in his official gamedata but I thought I'd open this just in case we need to fix more crashes soon
> Add new parameter in GetMissionVersusBossSpawning

- addons/sourcemod/scripting/changelog.sp
- addons/sourcemod/scripting/l4d2_antimelee.sp
- addons/sourcemod/scripting/l4d2_byedoor.sp
- addons/sourcemod/scripting/l4d2_smg_reload_tweak.sp
- addons/sourcemod/scripting/l4d2_smoker_drag_damage_interval_zone.sp
- addons/sourcemod/scripting/simple_witch_bonus.sp
- addons/sourcemod/scripting/slots_vote.sp
Final set of plugin reconstructions I could accurately recreate.
* simple_witch_bonus.sp - used older version as base
* l4d2_smoker_drag_damage_interval_zone.sp  - used l4d2_smoker_drag_damage_interval.sp as base
The rest were reconstructed without anything to start with except the lysis decompilations.
* l4d2_antimelee.sp
* l4d2_byedoor.sp
* l4d2_smg_reload_tweak.sp
* changelog.sp
* slots_vote.sp
Lysis decompilations aren't perfect, so I also checked each compiled reconstruction with the [disassembler webtool](https://peace-maker.github.io/sourcepawn-disassembler-web). I compared each disassembled reconstruction to a disassembly of the original smx and adjusted the reconstructed code until I ended up with no significant differences in instructions between the two. The only differences …
> More reconstructed plugins sources

- addons/sourcemod/scripting/si_fire_immunity.sp
Source I started with from https://github.com/Attano/L4D2-Competitive-Framework/blob/master/addons/sourcemod/scripting/si_fire_immunity.sp
I've been basing reconstructions off of decompilation comparisons generated using [lysis decompiler](https://github.com/peace-maker/lysis-java). The decompiler has some bugs that don't always give a correct interpretation of logic chains resulting in ambiguous output. I haven't seen this come up in previous plugin reconstructions, but this time I did with this line from the decompilation, which clearly isn't how the original source is supposed to look:
```
if (strcmp(weapon, "inferno", true) && attacker && strcmp(weapon, "entityflame", true))
```
I dug in deeper with this tool that lets you see the raw instructions …
> add si fire immunity source

- addons/sourcemod/scripting/include/l4d2_penalty_bonus.inc
- addons/sourcemod/scripting/include/l4d2_weapon_stocks.inc
- addons/sourcemod/scripting/l4d2_saferoom_item_remove.sp
* Added missing l4d2_weapon_stocks.inc which is used in l4d2_sniper_precache, l4d2_smg_reload_tweak, and l4d2_drop_secondary.
I first committed the version they were originally using when compiled with SM 1.6. Then I updated the include to fix the compilation for SM 1.10.
* Fixed implicit-int enum SM 1.10 compile error for l4d2_saferoom_item_remove.sp
* Fixed l4d2_penalty_bonus.inc PBONUS_AddRoundBonus native definition.
simple_witch_bonus calls this native and passes a second "no report" argument which isn't in the include native definition even though the implementation for the native in l4d2_penalty_bonus.sp has logic to check for and support the argument. I made it optional with a default value of false, because holdout_bonus also calls the same native with only a single argument. …
> SM 1.10 Compile fixes

- addons/sourcemod/scripting/1v1.sp
- addons/sourcemod/scripting/eq_finale_tanks.sp
- addons/sourcemod/scripting/finalefix.sp
- addons/sourcemod/scripting/include/mapinfo.inc
- addons/sourcemod/scripting/include/survivors.inc
- addons/sourcemod/scripting/l4d2_blind_infected.sp
- addons/sourcemod/scripting/l4d2_drop_secondary.sp
- addons/sourcemod/scripting/l4d2_getupfix.sp
- addons/sourcemod/scripting/l4d2_godframes_control_merge.sp
- addons/sourcemod/scripting/l4d2_health_temp_bonus.sp
- addons/sourcemod/scripting/l4d2_horde_equaliser.sp
- addons/sourcemod/scripting/l4d2_hunter_no_deadstops.sp
- addons/sourcemod/scripting/l4d2_hybrid_scoremod.sp
- addons/sourcemod/scripting/l4d2_hybrid_scoremod_zone.sp
- addons/sourcemod/scripting/l4d2_jockey_jumpcap_patch.sp
- addons/sourcemod/scripting/l4d2_meleecontrol.sp
- addons/sourcemod/scripting/l4d2_nobackjumps.sp
- addons/sourcemod/scripting/l4d2_saferoom_item_remove.sp
- addons/sourcemod/scripting/l4d2_scoremod.sp
- addons/sourcemod/scripting/l4d2_spec_stays_spec.sp
- addons/sourcemod/scripting/l4d2_tank_announce.sp
- addons/sourcemod/scripting/l4d2_tank_attack_control.sp
- addons/sourcemod/scripting/l4d2_tank_attack_control_nextmod.sp
- addons/sourcemod/scripting/l4d2_weapon_attributes.sp
- addons/sourcemod/scripting/l4d2_weaponrules.sp
- addons/sourcemod/scripting/l4d_stuckzombiemeleefix.sp
- addons/sourcemod/scripting/l4d_tank_control_eq.sp
- addons/sourcemod/scripting/l4d_weapon_limits.sp
- addons/sourcemod/scripting/readyup.sp
- addons/sourcemod/scripting/tankdoorfix.sp
* Corrected errors with MaxClients and MAXPLAYERS.
* Corrected a couple instances of unclosed handles
* Renamed event handlers whose names conflict with l4d2util global forwards (OnRoundStart, OnRoundEnd, OnTankSpawn) in plugins that don't include l4d2util and hook the events themselves, otherwise they fire twice (from plugin's own hook + l4d2util global forward).
* Added l4d2util include to plugins that rely on its OnRoundStart global forward because they don't hook round_start themselves. This just makes the dependency on l4d2util explicit.
> Small source code fixes/refactor

- addons/sourcemod/scripting/fix_engine.sp
- addons/sourcemod/scripting/l4d2_getupfix.sp
- addons/sourcemod/scripting/l4d2_nosey_parker.sp
Fixed leaked handles in l4d2_nosey_parker.sp and l4d2_getupfix.sp.
Tracked timers should be manually ended OnMapEnd instead of using TIMER_FLAG_NO_MAPCHANGE ([wiki reference](https://wiki.alliedmods.net/SourcePawn_Basics_-_Handles,_DataPacks,_and_Timers#.22Fire_and_Forget.22_vs._.22Tracked.22_Timers)), otherwise the variable will not be set to INVALID_HANDLE. Can also be fixed by setting the variable to INVALID_HANDLE which is the approach I used for fix_engine.sp.
Addresses the issue in https://github.com/SirPlease/L4D2-Competitive-Rework/pull/173
> fix handle leak and fix TIMER_FLAG_NO_MAPCHANGE usage

- addons/sourcemod/scripting/include/confogl.inc
- addons/sourcemod/scripting/include/mapinfo.inc
- addons/sourcemod/scripting/l4d2lib.sp
My attempt at fixing https://github.com/SirPlease/L4D2-Competitive-Rework/issues/103
I found through testing that the confogl natives weren't available OnMapStart (the very first time after the config is loaded but before the map is reloaded) since l4d2lib is loaded before confoglcompmod. so I moved MapInfo_Init from OnMapStart to OnLibraryAdded. This resolves the unbound native error.
Another thing I noticed is that currently kMIData gets initialized before the error is thrown in the next line that calls LGO_BuildConfigPath. https://github.com/SirPlease/L4D2-Competitive-Rework/blob/c20db7a6dd589b5fec364b1ed0d22c89244572e0/addons/sourcemod/scripting/include/mapinfo.inc#L182
Since kMIData is initialized, any calls to `GetMapValueInt` don't currently throw an error. But since this PR now …
> L4D2Lib unbound native fix

- addons/sourcemod/scripting/l4d2_weapon_attributes.sp
Fix for https://github.com/SirPlease/L4D2-Competitive-Rework/issues/169
Instead of storing a shifted weapon attribute index, it shifts the index in each iFloatWeaponAttributes lookup.
> fix float attribute reset OnPluginEnd

- cfg/stripper/zonemod/maps/c2m4_barns.cfg
Added a teleport trigger in fence props - teleports to center of room.
> Fix stuck survivors in c2m4 saferoom.

- addons/sourcemod/scripting/l4d2_setscores.sp
Fixes plugin 'l4d2_setscores.smx':
1) You can change points during voting, you need to execute the command again with your points. You can even be a spectator. 
2) If you enable the 'setscore_allow_player_vote' cvar, then the voting does not work for the admin if he is a spectator.
> Fix plugin l4d2_setscores.smx

- addons/sourcemod/scripting/l4d2_hittable_control.sp
- cfg/cfgogl/apex/shared_settings.cfg
- cfg/cfgogl/eq/shared_settings.cfg
- cfg/cfgogl/nextmod/shared_settings.cfg
- cfg/cfgogl/pmelite/pmelite.cfg
- cfg/cfgogl/zonemod/shared_settings.cfg
Plugin needs compiling.
Fixes issue #253 
Fixed hittable model name checks being case sensitive, which caused certain hittables to be ignored by the plugin (swamp fever log).
Replaces `\` characters with `/` in model name strings, using `/` in the model name check is now always valid.
Fixed overkill issues with concrete pillars found on No Mercy and custom campaigns.
Added various hittables that were missing from the plugin, and support for this version of the Blood Harvest finale chair:
https://github.com/Derpduck/L4D2-Comp-Stripper-Rework/blob/240c8d394b1c1f4f924fba7d2025b5569c1a7664/cfg/stripper/maps/c12m5_cornfield.cfg#L96
> Fix l4d2_hittable_control (issue #253)

- cfg/stripper/zonemod/maps/c5m2_park.cfg
- scripts/vscripts/director_onslaught_flow_checker.nut
- scripts/vscripts/director_onslaught_rework_c5m2.nut
* Fixed issues with horde warnings during event tanks, which was preventing the horde from relaxing as intended
* Added a sound cue for when the horde is resumed due to progression
Also fixes a perma-stuck spot that should have been included in the current version, I guess it got missed out.
> Fixed c5m2 onslaught event warningas

- addons/sourcemod/scripting/l4d2_nobhaps.sp
- check for perfect bhops instead of landing speed
- use `SetEntProp` instead of `TeleportEntity` for capping speed
- add extra convar `bhop_consecutive_hops_si` to allow for a certain number of hops on non-exempt SI (in case keeping old 1-bhop allowed behavior is desired)
[FIXED] ~~Known issue (was already present before and on every jump, not just perfect bhops):~~
~~- If you land a perfect hop while holding crouch, speed will be limited to crouch speed instead of max running speed, because the EntProp `m_flMaxspeed` is dependent on whether you're crouching or not. If someone knows a way to get max running speed it would be an easy fix, just replace the variable.~~
I've tested the plugin on as many scenarios as I could think of with no issues but further testing may be required.
> l4d2_nobhaps rework

- cfg/stripper/zonemod/global_filters.cfg
Revert change to prop fix for custom campaigns as it causes issues with breakable props.
Fixes the ball on the Diescraper finale not breaking.
> Fix Diescraper ball not breaking

- cfg/cfgogl/acemodrv/shared_plugins.cfg
Plugin was included by mistake, not used in Acemod, l4d2_tank_charger_m2_fix is used instead.
Double checked all other plugins being loaded in Acemod and all looked ok.
> Remove l4d2_melee_shenanigans from Acemod

- Dedicated Server Install Guide/srcds1
Fixed bug, when user might to execute "/etc/init.d/srcds1 start" 2 times or more. This led to the fact that the process was duplicated and thus it was possible to run several servers with the same process name (for example, "L4D2 Dedicated Server 1"), but with different ports. This fix, when you re-enter the command "/etc/init.d/srcds1 start", will give a message that the process has already started and will suspend further execution of the command.
> srcds1 "start" command micro-fix

- addons/sourcemod/scripting/slots_vote.sp
- Code rewritten to new syntax (use matchvote for reference).
- Replace (GetUserAdmin(client) != INVALID_ADMIN_ID) with
(GetUserFlagBits(client) & ADMFLAG_GENERIC), as it allowed users with custom flags to run the command.
- The slot change announcement by an administrator has been modified, now it will say the name of the client.
> slots_vote syntax

- addons/sourcemod/gamedata/l4d_fix_shove_duration.txt
> Fix `l4d_fix_shove_duration` crashing on windows

- addons/sourcemod/scripting/include/colors.inc
1) Code refactoring
2) Allow prints for SourceTV
Description: Many plugins use `CPrintToChatAll`, but checking `IsFakeClient` from sourcemod does not allow sending this print to SourceTV as well, so many messages are not displayed on the demo and during broadcast. Of course, this cannot be fixed without recompiling all plugins, so I decided to enable this feature by default.
> [Colors] Allow prints for SourceTV

- addons/sourcemod/scripting/confoglcompmod.sp
- addons/sourcemod/scripting/confoglcompmod/BossSpawning.sp
- addons/sourcemod/scripting/confoglcompmod/BotKick.sp
- addons/sourcemod/scripting/confoglcompmod/ClientSettings.sp
- addons/sourcemod/scripting/confoglcompmod/CvarSettings.sp
- addons/sourcemod/scripting/confoglcompmod/EntityRemover.sp
- addons/sourcemod/scripting/confoglcompmod/FinaleSpawn.sp
- addons/sourcemod/scripting/confoglcompmod/GhostTank.sp
- addons/sourcemod/scripting/confoglcompmod/GhostWarp.sp
- addons/sourcemod/scripting/confoglcompmod/ItemTracking.sp
- addons/sourcemod/scripting/confoglcompmod/MapInfo.sp
- addons/sourcemod/scripting/confoglcompmod/PasswordSystem.sp
- addons/sourcemod/scripting/confoglcompmod/ReqMatch.sp
- addons/sourcemod/scripting/confoglcompmod/ScoreMod.sp
- addons/sourcemod/scripting/confoglcompmod/UnprohibitBosses.sp
- addons/sourcemod/scripting/confoglcompmod/UnreserveLobby.sp
- addons/sourcemod/scripting/confoglcompmod/WaterSlowdown.sp
- addons/sourcemod/scripting/confoglcompmod/WeaponCustomization.sp
- addons/sourcemod/scripting/confoglcompmod/WeaponInformation.sp
- addons/sourcemod/scripting/confoglcompmod/includes/configs.sp
- addons/sourcemod/scripting/confoglcompmod/includes/customtags.sp
- addons/sourcemod/scripting/confoglcompmod/includes/debug.sp
- addons/sourcemod/scripting/confoglcompmod/includes/survivorindex.sp
1) Fix warnings on sm 1.12
2) Removed unnecessary public access modifiers
> [confoglcompmod] Fix warnings on sm 1.12

- cfg/cfgogl/zonemod/mapinfo.txt
[dead before dawn dc]
*map 4:
unlock 36%-49%;
adjust value of 'through vent';
from 67%-75% to 73%-75%;
[open road]
map 2:
ban 82%-100%;
tank has to chase survivors from behind,  survivors can rush to the safe room without fighting the tank.
[trip day]
map 3:
ban 0%-27%;
this distance was early to survivors trigger a tank.
> adjust [dbd dc/open road/ trip day] tank-ban percent

- addons/sourcemod/translations/annoyance_exploit_fixes.phrases.txt
- addons/sourcemod/translations/es/1v1.phrases.txt
- addons/sourcemod/translations/es/1v1_skeetstats.phrases.txt
- addons/sourcemod/translations/es/8ball.phrases.txt
- addons/sourcemod/translations/es/annoyance_exploit_fixes.phrases.txt
- addons/sourcemod/translations/es/blocktrolls.phrases.txt
- addons/sourcemod/translations/es/checkpoint-rage-control.phrases.txt
- addons/sourcemod/translations/es/l4d2_skill_detect.phrases.txt
- addons/sourcemod/translations/es/l4d2_stats.phrases.txt
- addons/sourcemod/translations/es/l4d2_tank_announce.phrases.txt
- addons/sourcemod/translations/es/l4d_boss_percent.phrases.txt
- addons/sourcemod/translations/es/l4d_boss_vote.phrases.txt
- addons/sourcemod/translations/es/nodeathcamskip.phrases.txt
- addons/sourcemod/translations/es/pause.phrases.txt
- addons/sourcemod/translations/es/playermanagement.phrases.txt
- addons/sourcemod/translations/es/slots_vote.phrases.txt
- addons/sourcemod/translations/es/spechud.phrases.txt
- addons/sourcemod/translations/es/tank_rush.phrases.txt
- addons/sourcemod/translations/es/tpsblock.phrases.txt
SourceMod 12 generates an error if a translation does not exist in an optional language. Normally, some translations like "Tag" were only created in the default language, omitting their translation into other languages, which is now considered an error.
+ 1v1_skeetstats: fixed translation error
+ annoyance_exploit_fixes: modified and separated the Spanish translation
+ nodeathcamskip: created the Spanish translation
+ spechud.phrases: created the Spanish translation
+ l4d2_skill_detect.phrases: modified some translation lines to synthesize the message idea.
> SourceMod 12 fix translation

- cfg/stripper/zonemod/maps/c10m2_drainage.cfg
Block pillar top of the bridge
> fix a spot (svv cant revive) in c10m2 event

- cfg/cfgogl/zonemod/mapinfo.txt
new tank-ban-flow
--- [trip day match] ---
m1: none
m2: 
early (0~28%)
cornfield (36%~66%)
down the ladder (71%~100%)
m3: 
near building (74%~100%)
m4: 
early spawn (0%~32%)
m5: 
near gas station (52%~100%)
--- [no echo match] ---
m1: 
alarmcar (0%~40%)
m2: 
riverside (0%~35%)
m3: 
parking area (0%~43%)
alarmcar (47%~51%)
m4: 
container route (71%~100%)
m5: 
alarmcar (42%~50%)
> [mapinfo] adjust tank ban precent for [no echo/trip day]

- cfg/stripper/zonemod/maps/c4m3_sugarmill_b.cfg
avoid svv from being locked out of the elevator the moment it closes,
In theory, in this way, it is not guaranteed to solve the problem 100%, but it can also greatly reduce the possibility of problems.
In addition, the Svv bots will stand on the edge of the elevator and you will need to "push" them into the elevator (this only happens if you lack 2+ player teammates).
> [map fix : c4m3] adjust postion of elevt trigger area

- cfg/stripper/zonemod/maps/cdta_01detour.cfg
- cfg/stripper/zonemod/maps/cdta_02road.cfg
- cfg/stripper/zonemod/maps/cdta_03warehouse.cfg
- cfg/stripper/zonemod/maps/cdta_04onarail.cfg
Map 1
1. Remove 2 pill spawns outside the map
2. Block survivors from getting back to saferoom by standing on the edge of a rock by the one-way-drop
Map 2
1. Remove pill spawns outside the map
2. Block a big shortcut before the event: https://youtu.be/pDNYct34aaE
Map 3
1. Remove a pill spawn outside the map
Map 4
1. Remove a pill spawn outside the map
2. Block stuck spots, add an infected ladder at a stuck spot
> Detour Ahead Fixes

- cfg/server.cfg
The standard value of 4 can cause significant issues with choke and incorrect tick display on the client side. If this value is reduced to less than 1 tick but not below 0, choke no longer occurs, and hit registration improves due to more frequent packet transmission from the client to the server and vice versa.
> Fix incorrect display of ticks in client

- addons/sourcemod/scripting/include/lerpmonitor.inc
- addons/sourcemod/scripting/lerpmonitor.sp
1) Removed unnecessary checks in native 'LM_GetLerpTime'. 'GetClientAuthId' - will abort the code on error (If the client is not connected or the index is invalid).
2) Removed unnecessary checks in native 'LM_GetCurrentLerpTime'. 'GetClientInfo' - will abort the code on error (If the client is not connected or the index is invalid).
3) Added native 'LM_GetChachedLerpTime'. Native returns the stored lerp time for the player.
4) Changed native 'LM_GetLerpTime'. Native now returns the player's saved interpolation time, if the interpolation value is not found in the array, then it gets and returns the player's current interpolation time.
> [Lerpmonitor] Update

- cfg/stripper/acemodrv/maps/c1m4_atrium.cfg
- cfg/stripper/neomod/maps/c1m4_atrium.cfg
- cfg/stripper/zonemod/maps/c1m4_atrium.cfg
When the elevator descends, the model remains in place
> Fix elevator rail for c1m4_atrium

- .github/workflows/check_plugins.yml
Let the script to compile ALL the plugins, count the failed plugin compilations, and depending on the result produce an adequate exit code.
Currently the script stops on the first failed plugin compilation error.
But in case more plugins fail to compile, we don't exactly know which ones failed except the first one.
> Let the plugin check workflow loop continue after the first error

- addons/sourcemod/scripting/l4d2_nobhaps.sp
1) Updated syntax.
2) Removed unnecessary checks and unnecessary code. 
3) Added command 'sm_check_bhop' to check  plugin cvars, for more convenient configuration (shows for which classes of infected bhop is disabled). 
4) The plugin has been working on servers for a long time and has been tested.
> Updated 'l4d2_nobhaps'

- addons/sourcemod/scripting/current.sp
- addons/sourcemod/scripting/l4d2_tankrage.sp
current check sometimes returns a null nav area
example: c1m1_hotel, teleport to the position "300 5683 2893"
the current flow displayed by the plugin outputs "14%" because the "flow" variable is 0, because no nav (pNavArea) was found
using "L4D_GetLastKnownArea" is more accurate since it outputs the same value as the "current_flow_distance" game command
> Fix plugin returning a null nav area when based on player origin
