SirPlease/L4D2-Competitive-Rework

- addons/sourcemod/scripting/include/l4d2util_weapons.inc
Noticed this bug fix that was in ConfoglTeam's l4d2util repo that was missing here https://github.com/ConfoglTeam/l4d2util/commit/53c9d76da9d1ba5fcbfec062b3e0422dd6e1ee16
> fixed model empty string check

- addons/sourcemod/scripting/l4d2_saferoom_detect.sp
Updated reference to lgofnoc with confogl.
> Saferoom Detect update

- addons/sourcemod/scripting/confoglcompmod.sp
- addons/sourcemod/scripting/modules/EntityRemover.sp
- addons/sourcemod/scripting/modules/GhostWarp.sp
- addons/sourcemod/scripting/modules/ItemTracking.sp
- addons/sourcemod/scripting/modules/MapInfo.sp
- addons/sourcemod/scripting/modules/PasswordSystem.sp
- addons/sourcemod/scripting/modules/SI_Targeting.sp
Went through the confoglcompmod sources and fixed issues with MAXPLAYERS, MaxClients, and GetEntityCount() loops.
> fix off by one errors with MAXPLAYERS, MaxClients, and entity loops

- addons/sourcemod/scripting/l4d2_tank_attack_control_nextmod.sp
Fixes:
1) warning 217: loose indentation
2) [SM] Exception reported: Client 6 is not in game
[SM] Blaming: l4d2_tank_attack_control_nextmod.smx
[SM] Call stack trace:
[SM]   [0] ThrowError
[SM]   [1] Line 59, .\include\colors.inc::CPrintToChat
[SM]   [2] Line 219,.\l4d2_tank_attack_control_nextmod.sp::ResetJumpRockCooldown
3) Unnecessary "client" parameter on Timer_Countdown
4) Unnecessary IsClientConnected removed (IsClientInGame implies IsClientConnected)
5) Removed extra spaces, changed "4 spaces" to "tab" and removed extra line breaks \n\n\n to \n\n
> l4d2_tank_attack_control_nextmod minor changes

- Dedicated Server Install Guide/README.md
Minor dead link fix in Install Guide Readme
> Update link to srcds1 in readme

- cfg/stripper/zonemod/global_filters.cfg
> #234 Fix wrong physics prop class on custom campaigns

- scripts/vscripts/director_onslaught_rework_c5m2.nut
tank_death doesn't fire when a player controlled tank dies, makes sense... 🙃
> Fix c5m2 onslaught events (again)

- cfg/stripper/zonemod/maps/c5m2_park.cfg
- cfg/stripper/zonemod/maps/c5m3_cemetery.cfg
- scripts/vscripts/director_onslaught_rework_c5m2.nut
Forgot to push some changes to Github, these are already included in the ZM 2.1 changelog.
> Missing 2.1 changes

- addons/sourcemod/scripting/l4d2_nobhaps.sp
revert back to old anti bhop plugin method but with crouching speed issue fixed due to issues outlined in https://github.com/SirPlease/L4D2-Competitive-Rework/issues/290#issuecomment-868826933_
> Revert to old nobhop plugin method

- cfg/stripper/zonemod/maps/c1m3_mall.cfg
- cfg/stripper/zonemod/maps/cdta_04onarail.cfg
Fixes issue with c1m3 and cdta4 events not ending when hitting end trigger.
> Fix events not ending correctly

- cfg/stripper/zonemod/maps/c8m1_apartment.cfg
* Fixed an exploit blocker to get out of bounds by the saferoom
* Fixed blocker on AC unit by the saferoom being misplaced
> Fix c8m1 exploit blockers

- addons/sourcemod/scripting/l4d2_fix_spawn_order.sp
no logical/functional changes, just code cleanup and syntax update
This plugin could definitely use some further code cleanup but it would require more extensive testing then :)
> rewrite l4d2_fix_spawn_order.sp with transitional syntax

- Dedicated Server Install Guide/README.md
Added a step to avoid dos-line error when running srcds1
> Add a step to README.md to avoid dos-line error when running srcds1

- .github/workflows/check_plugins.yml
Add github actions to check plugins on multiple versions of sourcemod, if plugins or includes have been changed.
- 1.10
- 1.11
- 1.12 (latest)
> Add github actions.

- addons/sourcemod/scripting/nm3_ladder_damage.sp
1) Update syntax
2) Code optimization and fixing incorrect code related to netprops ('GetEntProp' incorrect to use with type EHANDLE netprops, it is correct to use 'GetEntPropEnt' in this case).
> [nm3_ladder_damage] Update plugin.

- .github/workflows/check_plugins.yml
1) Update version 'actions/checkout@v3' to prevent warnings.
2) Plugin checking was not triggered when changing files from folders other than 'scripting'. For example file: 'addons/sourcemod/scripting/confoglcompmod/ItemManager.sp'.
> Update github actions

- addons/sourcemod/translations/l4d2_skill_detect.phrases.txt
- addons/sourcemod/translations/tank_rush.phrases.txt
- Fix wrong message for Tank rush **unfreeze**
- Remove double-spacing for skill detect in **Shoving**
> Translation fixes

- addons/sourcemod/gamedata/FollowTarget_Detour.txt
- addons/sourcemod/gamedata/l4d_fix_finale_breakable.txt
- l4d_fix_finale_breakable
- FollowTarget_Detour
> Update gamedata for 2.2.2.8

- cfg/stripper/acemodrv/maps/c3m3_shantytown.cfg
- cfg/stripper/neomod/maps/c3m3_shantytown.cfg
- cfg/stripper/zonemod/maps/c3m3_shantytown.cfg
Update **c3m3_shantytown** stripper
Block a second perma-stuck spot behind a shrub wall near the first fire barrel
This is my first attempt at creating this type of treatment on the game's maps, if I did something wrong or something that could be improved, please let me know.
> update c3m3_shantytown stripper

- addons/sourcemod/scripting/include/l4d2_playstats.inc
- addons/sourcemod/scripting/l4d2lib.sp
```[SM] Exception reported: Invalid game event handle 0 (error 4)
[SM] Blaming: optional/l4d2lib.smx
[SM] Call stack trace:
[SM] [0] Event.GetInt
[SM] [1] Line 86, l4d2lib/mapinfo.sp::MapInfo_PlayerDisconnect_Event
[SM] [2] Line 216, l4d2lib.sp::PlayerDisconnect_Event
```
> [l4d2lib] Fix error message

- cfg/cfgogl/zonemod/shared_settings.cfg
- cfg/stripper/zonemod/maps/cwm3_drain.cfg
- cfg/stripper/zonemod/maps/hf01_theforest.cfg
fix a SI cheats spot that Si can get bottom of map
> fix a haunted forest spot

- addons/sourcemod/scripting/include/readyup.inc
- cfg/cfgogl/zonemod/shared_settings.cfg
- cfg/stripper/zonemod/maps/cwm3_drain.cfg
- cfg/stripper/zonemod/maps/hf01_theforest.cfg
- cfg/stripper/zonemod/maps/l4d2_ff01_woods.cfg
- cfg/stripper/zonemod/maps/l4d2_ff02_factory.cfg
just do my best to create a support for fatal freight map.
- with a lots of play and test
- enough spawn spot and Si ladder
- obstacle pills
- remove superfluous hittables
> make a full balanced modify for [fatal freight]

- addons/sourcemod/scripting/l4d2_playstats.sp
1) Removed unnecessary access modifiers - public
2) Code nesting reduced
3) Removed unnecessary checks in loops, removed macros from conditions
4) Removed duplicate checks inside conditions
To improve code readability? :D
> [l4d2_playstats] Update

- addons/sourcemod/gamedata/l4d2_ladderrambos.txt
> l4d2_ladder_rambos: Update gamedata

- cfg/stripper/zonemod/maps/c4m3_sugarmill_b.cfg
by change a angles of an entity clip wall
> fix a stuck spot (cant get out) in c4m3

- cfg/cfgogl/zonemod/mapinfo.txt
- cfg/stripper/zonemod/maps/c4m3_sugarmill_b.cfg
- cfg/stripper/zonemod/maps/l4d2_city17_01.cfg
- cfg/stripper/zonemod/maps/l4d2_city17_02.cfg
- cfg/stripper/zonemod/maps/l4d2_city17_03.cfg
- cfg/stripper/zonemod/maps/l4d2_city17_04.cfg
- cfg/stripper/zonemod/maps/l4d2_city17_05.cfg
- scripts/vscripts/l4d2_city17_05_finale_rework.nut
for modify details : https://github.com/AidenVii/Aiden_ZM_Custom_Maps_Moddify/wiki/City-17
>  [stripper support] full balance modify [city 17]

- cfg/cfgogl/zonemod/shared_settings.cfg
[city 17] map2 : elevator
[no echo] map1 : elevator
> [map spit block] add [city 17][no echo: match]

- cfg/stripper/zonemod/maps/l4d2_city17_03.cfg
- cfg/stripper/zonemod/maps/l4d2_city17_04.cfg
map 3: fix a pills position
map 4: fix the button IO logic
thanks @harry report
> fix some bugs of [city 17] stripper file

- cfg/stripper/zonemod/maps/cwm2_warehouse.cfg
- cfg/stripper/zonemod/maps/cwm4_building.cfg
map 2 stuck spot: https://youtu.be/GwmeN72Ti8I?feature=shared&t=1582
map 4 stuck spot: https://www.bilibili.com/video/BV15U4y1Q7z2/?share_source=copy_web&vd_source=62443208dd880e3e8b6bba31116ba2ba&t=3051
blocker preview
> Carried Off stuck spots fix

- Dedicated Server Install Guide/README.md
https://github.com/ValveSoftware/steam-for-linux/issues/11522#issuecomment-2512232264
> fix Invalid platform error of SteamCMD

- addons/sourcemod/scripting/charger_incap_damage.sp
1) Removed unnecessary checks and code
2) Fixed the problem that the plugin does not work if z_charger_pound_dmg is not equal to 15
> [charger_incap_damage] Update

- cfg/stripper/zonemod/maps/uf3_harbor.cfg
block 5 stuck spots near waterfront
#831
> map fix in [urban flight] m3

- cfg/stripper/zonemod/maps/l4d2_diescraper4_top_361.cfg
Video demonstration of the fix [https://dl.l4d2center.com/fl/d8/r9/sk/fa/v6/a9/1060306.2000000011_1717FC2EBF3456D6.mp4](https://dl.l4d2center.com/fl/d8/r9/sk/fa/v6/a9/1060306.2000000011_1717FC2EBF3456D6.mp4)
Fix provided by Aiden
> Block Diescraper map 4 shortcut

- cfg/stripper/acemodrv/maps/c6m2_bedlam.cfg
- cfg/stripper/deadman/maps/c11m4_terminal.cfg
- cfg/stripper/deadman/maps/c2m1_highway.cfg
- cfg/stripper/nextmod/maps/c2m1_highway.cfg
- cfg/stripper/zonemod/maps/c6m1_riverbank.cfg
- cfg/stripper/zonemod/maps/c6m2_bedlam.cfg
- cfg/stripper/zonemod/maps/c7m1_docks.cfg
- cfg/stripper/zonemod/maps/l4d2_city17_04.cfg
> stripper fixes
